EXTENSION = ednb              # the extension name
DATA      = ednb--0.0.1.sql   # script files to install
MODULES   = ednb

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
